-- Seed data matching app/content/edgexJobs.ts SEED_JOBS — run this to
-- populate the real jobs table with the same 14 postings the app
-- falls back to locally when this table is empty. Safe to re-run (upserts on id).
-- Run this AFTER edgex_schema.sql.

insert into public.jobs
  (id, title, department, location, location_category, employment_type, role, field, summary, description, requirements, posted_at, active, job_identification, full_address, base_pay_salary, responsibilities, preferred_qualifications)
values
  ('qpu-design-engineer', 'QPU Design Engineer', 'Quantum Engineering Division', 'Charlotte, NC (On-site)', 'Charlotte, NC', 'Full-time', 'Engineering', 'Quantum Hardware', 'Architect superconducting and photonic qubit designs for the QPU-X and QPU-P product lines.', 'You''ll work across coherence, gate-error, and connectivity tradeoffs for EDGEX''s custom QPU lines, partnering with fabrication and cryogenics to take designs from simulation to shipped hardware.', '["Graduate degree in physics, EE, or related field","Experience with superconducting or photonic qubit architectures","Familiarity with cryogenic system constraints (10–20 mK)","Working knowledge of pulse-level control and gate calibration"]', '2026-07-01', true, 'EDGX-2026-01142', null, null, '[]', '[]'),
  ('cryogenic-systems-engineer', 'Cryogenic Systems Engineer', 'Quantum Engineering Division', 'Charlotte, NC (On-site)', 'Charlotte, NC', 'Full-time', 'Engineering', 'Quantum Hardware', 'Design and maintain the dilution refrigeration and RF/microwave control stack for EDGEX''s QPU fleet.', 'You''ll own the cryogenic control systems product line — dilution refrigerator integration, RF/microwave signal chains, and the pulse-level firmware that drives gate operations at 10–20 mK.', '["Experience with dilution refrigerator systems","RF/microwave engineering background","Comfort with low-level firmware for timing-critical control loops","Experience troubleshooting cryogenic thermal and vibration issues"]', '2026-06-15', true, 'EDGX-2026-01187', null, null, '[]', '[]'),
  ('quantum-error-correction-scientist', 'Quantum Error Correction Research Scientist', 'Research & Innovation Lab', 'Charlotte, NC (On-site) or Remote (US)', 'Charlotte, NC', 'Full-time', 'Research', 'Error Correction', 'Develop and benchmark error-correcting codes across EDGEX''s five QPU architectures.', 'You''ll research surface codes, cat codes, and topological error correction schemes, and work with Quantum Engineering to validate which codes are practical on which hardware modality — a core input to the fault-tolerant QPU-T roadmap.', '["PhD or equivalent research experience in quantum information theory","Familiarity with surface codes and/or topological error correction","Experience benchmarking logical error rates against physical noise models","Publication record in quantum error correction preferred"]', '2026-07-10', true, 'EDGX-2026-01256', null, null, '[]', '[]'),
  ('error-correction-engineer', 'Quantum Error Correction Engineer', 'Quantum Engineering Division', 'Charlotte, NC (On-site)', 'Charlotte, NC', 'Full-time', 'Engineering', 'Error Correction', 'Implement error-correcting code layers in EDGEX''s control firmware and calibration pipelines.', 'You''ll translate error-correction research into shipped firmware — syndrome extraction, decoder integration, and real-time feedback loops running on the QPU control electronics.', '["Strong background in digital signal processing or real-time control systems","Familiarity with quantum error correction concepts (syndrome measurement, decoding)","Experience with FPGA or low-latency embedded firmware"]', '2026-07-05', true, 'EDGX-2026-01261', null, null, '[]', '[]'),
  ('quantum-software-engineer-qml', 'Quantum Software Engineer (QML)', 'Quantum Software Division', 'Remote (US)', 'Remote (US)', 'Full-time', 'Engineering', 'Quantum Machine Learning', 'Build hybrid quantum-classical QML pipelines for financial and healthcare clients.', 'You''ll implement variational circuits, quantum kernels, and QNNs, and integrate them with classical ML pipelines running on Azure Quantum and AWS Braket.', '["Strong Python background","Experience with a quantum SDK (Qiskit, Cirq, or PennyLane)","Comfort working across classical ML and quantum toolchains"]', '2026-07-08', true, 'EDGX-2026-01309', null, null, '[]', '[]'),
  ('principal-quantum-algorithms-scientist', 'Principal Quantum Algorithms Scientist', 'Research & Innovation Lab', 'Charlotte, NC (On-site) or Remote (US)', 'Charlotte, NC', 'Full-time', 'Research', 'Quantum Machine Learning', 'Lead algorithm research for EDGEX''s QML Suite across variational circuits, QNNs, and QAOA.', 'You''ll set technical direction for the algorithms underneath the QML Suite, evaluating new variational architectures and optimization techniques before they move into the Quantum Software Division''s production pipeline.', '["PhD in quantum computing, physics, or computer science","Deep familiarity with variational quantum algorithms and QAOA","Track record leading applied research from prototype to production handoff"]', '2026-06-28', true, 'EDGX-2026-01198', null, null, '[]', '[]'),
  ('senior-quantum-ml-engineer-finance', 'Senior Quantum ML Engineer, Finance', 'Quantum Software Division', 'New York, NY or Remote (US)', 'New York, NY', 'Full-time', 'Engineering', 'Quantum Finance', 'Build QAOA-based portfolio optimization and quantum Monte Carlo pricing tools for trading-desk clients.', 'You''ll own the finance-facing slice of the QML Suite — portfolio allocation, derivatives pricing, and risk aggregation models — working directly with client quant teams during PoC and production engagements.', '["Experience with quantitative finance (derivatives pricing, portfolio optimization)","Hands-on experience with QAOA or quantum amplitude estimation","Comfort working directly with client quant/trading teams"]', '2026-07-12', true, 'EDGX-2026-01334', null, null, '[]', '[]'),
  ('quantitative-researcher-quantum-finance', 'Quantitative Researcher, Quantum Finance', 'Research & Innovation Lab', 'New York, NY', 'New York, NY', 'Full-time', 'Research', 'Quantum Finance', 'Research quantum algorithms for derivatives pricing, time-series forecasting, and risk modeling.', 'You''ll develop and validate quantum Monte Carlo and amplitude estimation approaches to derivatives pricing, and hybrid quantum-classical models for time-series forecasting, ahead of handoff to the finance engineering team.', '["Graduate degree in a quantitative field (financial engineering, physics, applied math)","Experience with Monte Carlo pricing methods","Familiarity with quantum amplitude estimation a strong plus"]', '2026-06-20', true, 'EDGX-2026-01102', null, null, '[]', '[]'),
  ('quantum-risk-modeling-analyst', 'Quantum Risk Modeling Analyst', 'Quantum Software Division', 'Remote (US)', 'Remote (US)', 'Full-time', 'Data Science', 'Quantum Finance', 'Build quantum-enhanced risk aggregation and stress-testing models for portfolio clients.', 'You''ll develop risk models for portfolios with complex, non-linear dependency structures, using quantum-enhanced simulation to capture correlation effects classical models tend to miss.', '["Background in quantitative risk modeling","Experience with portfolio stress-testing methodologies","Python proficiency; quantum computing exposure a plus, not required"]', '2026-07-14', true, 'EDGX-2026-01358', null, null, '[]', '[]'),
  ('quantum-fraud-detection-data-scientist', 'Quantum Fraud Detection Data Scientist', 'Quantum Software Division', 'Remote (US)', 'Remote (US)', 'Full-time', 'Data Science', 'Fraud & Anomaly Detection', 'Build quantum kernel and QNN-based anomaly detection models for transaction fraud detection.', 'You''ll design quantum-enhanced anomaly detection models for high-dimensional transaction data, working with client fraud and risk teams to integrate them into existing detection pipelines.', '["Experience building fraud/anomaly detection models in production","Familiarity with quantum kernel methods or QNNs","Comfort working with imbalanced, high-dimensional transactional data"]', '2026-07-16', true, 'EDGX-2026-01372', null, null, '[]', '[]'),
  ('ml-engineer-anomaly-detection', 'Machine Learning Engineer, Anomaly Detection', 'Quantum Software Division', 'Remote (US)', 'Remote (US)', 'Full-time', 'Engineering', 'Fraud & Anomaly Detection', 'Productionize hybrid quantum-classical anomaly detection pipelines for cybersecurity and finance clients.', 'You''ll take anomaly detection models from research prototypes to production services — orchestration, monitoring, and integration with client-side threat detection and fraud systems.', '["Strong software engineering background (Python, production ML systems)","Experience deploying anomaly/threat detection models at scale","Familiarity with hybrid quantum-classical pipeline orchestration a plus"]', '2026-07-18', true, 'EDGX-2026-01381', null, null, '[]', '[]'),
  ('nuclear-systems-engineer', 'Nuclear Systems Integration Engineer', 'Advanced Energy Systems Division', 'Charlotte, NC (On-site)', 'Charlotte, NC', 'Full-time', 'Engineering', 'Energy Systems', 'Integrate micro-modular reactor (MMR) power modules with quantum data center infrastructure.', 'You''ll work at the boundary between reactor core partners and EDGEX''s facility architecture — power distribution, containment monitoring, and fail-safe protocol integration.', '["Background in nuclear or power systems engineering","Experience with regulatory/compliance documentation","Comfort working alongside external NRC-compliant engineering partners"]', '2026-06-20', true, 'EDGX-2026-00987', null, null, '[]', '[]'),
  ('enterprise-solutions-consultant', 'Enterprise Solutions Consultant', 'Enterprise Solutions Division', 'Remote (US)', 'Remote (US)', 'Full-time', 'Consulting & Delivery', 'Enterprise Solutions', 'Lead client readiness assessments and PoC delivery across finance, healthcare, and defense accounts.', 'You''ll scope quantum readiness for enterprise clients, run proof-of-concept engagements, and hand off production architecture to the Engineering and Software divisions.', '["5+ years in technical consulting or solutions architecture","Ability to translate quantum capabilities into business outcomes","Experience with enterprise procurement and compliance cycles"]', '2026-07-15', true, 'EDGX-2026-01366', null, null, '[]', '[]'),
  ('principal-swe-agentic-quantum-ai', 'Principal Software Engineer, Agentic Quantum AI Platforms', 'Quantum Software Division', 'Bayonne, NJ (On-site)', 'Bayonne, NJ', 'Full-time', 'Engineering', 'Quantum Machine Learning', 'Lead architecture and hands-on development of the agentic orchestration layer behind the EDGEX QML Suite — the system that coordinates quantum and classical workloads across client engagements.', 'As Principal Software Engineer on the Quantum Software Division''s platform team, you''ll lead the design, build, and scaling of the agentic orchestration layer underneath the EDGEX QML Suite — the system that decides which parts of a hybrid pipeline run on quantum hardware, which run classically, and how multi-step reasoning, retrieval, and tool use are coordinated across both. This is a hands-on role: you''ll write production code, make key architectural calls, and be accountable for what ships, while also setting the multi-year direction for the platform.', '["8+ years in software engineering, including experience leading architecture for large distributed systems","Expert-level Python; strong working proficiency in TypeScript or Rust","Hands-on experience with agentic/orchestration frameworks (LangGraph, AutoGen, or equivalent)","Strong grounding in retrieval-augmented generation, tool/function calling, and multi-step reasoning patterns","Distributed systems experience: message queues, gRPC/REST, containerized deployment (Docker/Kubernetes)","Comfort designing systems that route work across quantum and classical execution backends"]', '2026-07-27', true, 'EDGX-2026-04721', '20 Port Jersey Blvd, Bayonne, NJ 07002, US', 'Bayonne, NJ $195,000.00–$260,000.00', '["Own the multi-year strategy for the QML Suite''s agentic orchestration layer — toolchains, retrieval pipelines, state management, and evaluation loops","Architect the routing logic that decides which pipeline stages run on EDGEX QPUs versus classical compute, and define clear primitives for when each applies","Establish standards for the platform''s development lifecycle: evaluation, observability, security review, and release readiness","Contribute directly in Python — services, concurrency, reliability — and set the bar through reference implementations","Lead design and code reviews; participate directly in incident response and production hardening","Build reusable agent components: task decomposition, tool/function calling, self-critique loops, and multi-agent coordination","Partner with the Research & Innovation Lab on moving new orchestration techniques from prototype into the production platform"]', '["Experience with quantum SDKs (Qiskit, Cirq, or PennyLane)","Background in financial services or another regulated, high-stakes domain","Publications, talks, or open-source contributions related to agentic AI systems"]')
on conflict (id) do update set
  title = excluded.title,
  department = excluded.department,
  location = excluded.location,
  location_category = excluded.location_category,
  employment_type = excluded.employment_type,
  role = excluded.role,
  field = excluded.field,
  summary = excluded.summary,
  description = excluded.description,
  requirements = excluded.requirements,
  posted_at = excluded.posted_at,
  active = excluded.active,
  job_identification = excluded.job_identification,
  full_address = excluded.full_address,
  base_pay_salary = excluded.base_pay_salary,
  responsibilities = excluded.responsibilities,
  preferred_qualifications = excluded.preferred_qualifications;
